---
- name: unencrypted AMI
  hosts: localhost
  tasks:
  - name: show all unencrypted IAM status
    shell: aws ec2 describe-volumes --filters Name=encrypted,Values=false

#    shell: aws ec2 describe-images --image-ids ami-00399ec92321828f5 --region us-east-2 --query Images[*].BlockDeviceMappings
#  - name: fact about AMI
#    ec2_ami_info:
#    filters:
#        name: ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210430
#      region: us-east-2
  - name: aws acount details like account number
    shell: aws iam get-user
  - name: aws profile information
    aws_caller_info:
    register: output
  - debug:
      var: output
  - name: collect all output in a file
    copy:
      content: "{{ output}}"
      dest: "AMIoutput.txt"
